### PR TITLE
update travis.yml

### PR DESCRIPTION
**Pull request by k-okada**
Created travis.yml using
- https://github.com/ros-infrastructure/ros_buildfarm/blob/master/doc/jobs/devel_jobs.rst
- https://github.com/ros-infrastructure/ros_buildfarm/blob/master/doc/jobs/prerelease_jobs.rst

Please activate GitHub - TravisCI integration to enable this test
https://github.com/apps/travis-ci

### CODE REVIEW

**Comment by k-okada** [comment]
@d-nakamichi can we enable TravsiCI ?

Go through the instructution here 
https://qiita.com/hoshimado/items/4090d8e64beb8a7f95e1#travis-ci%E3%82%A2%E3%82%AB%E3%82%A6%E3%83%B3%E3%83%88%E4%BD%9C%E6%88%90%E3%81%A8%E5%AF%BE%E8%B1%A1%E3%81%AEgithub%E3%83%AA%E3%83%9D%E3%82%B8%E3%83%88%E3%83%AA%E3%82%92%E7%B4%90%E4%BB%98%E3%81%91
Until “これで、Travis CI側の設定は完了。”

**Comment by d-nakamichi** [comment]
Thanks for your help!
Now I activated GitHub - TravisCI integration.

**Comment by gavanderhoorn** [comment]
@k-okada: did you have any particular reason not to use [industrial_ci](https://github.com/ros-industrial/industrial_ci)? It's not a panacea, but leads to very readable and simple `.travis.yml` files (see [this one](https://github.com/ros-industrial/industrial_core/blob/a588028a74a654af3dc06803b9cf6031d3b960e8/.travis.yml) as an example).

**Comment by gavanderhoorn** [comment]
@k-okada: it appears you merged an older version of https://github.com/Kawasaki-Robotics/khi_robot/compare/master...gavanderhoorn:pkging_updates.

**Comment by k-okada** [comment]
@gavanderhoorn yes, i know. I just want travis to answer 

> @k-okada: could you verify this also works for you?

question.

Please wait at most 16 hours, I will finalize this PR and ready to merge and release working version so that we can put khi_robot to the this week's sync.

**Comment by gavanderhoorn** [comment]
Your proposed travis config is not working because it also includes an Indigo build. The IKFast plugins cannot build under Indigo.

**Comment by d-nakamichi** [comment]
@k-okada @gavanderhoorn 
* `industrial_ci`
* `prerelease.sh`

Which is better?
For testing just build/install package, `industrial_ci` seems better because it can select `prerelease` or not.
[Run ROS Prerelease Test](https://github.com/ros-industrial/industrial_ci/blob/master/doc/index.rst#run-ros-prerelease-test)

**Comment by k-okada** [comment]
@d-nakamichi @matsui-hiro @gavanderhoorn Although 2c0a73e did not failed as I expected, but  I think this PR is ready to merge and release.

==
> @k-okada: did you have any particular reason not to use industrial_ci? 

1) ros_buildfarm is less likely to loose maintainer, If ros_buildfarm is orphaned and we have no alternatives, that’s mean the end of ROS. For example, every time we have new ROS distro or new Ubuntu version, we can assume it is OSRF jobs to update the ros_buildfirm to support them. But as for industrial_ci, someone have to do that. (In my opinion, if ROS-I have the resource to maintain industrial_ci that effort should goes to maintain image_pipeline, rqt, ros-drivers,,, and so on...)

2) My understanding of industrial_ci is customizable, (At least originally, because that is originally coms from our http://github.com/jsk-ros-pkg/jsk_travis ) So when the source tree did not pass the travis we have opetion to customize the CI parts, for example skip some package, run extra scripts and so on...., and it is good compromise between stability vs development speed, for research labs. But for industrial application, stability is much important. So if we do not pass the travis, we should fix source tree.  (So ideally, we should run build script, in addition to prerelease, becoause our intrest is if the source tree is able to run on the buildfirm.)

**Comment by d-nakamichi** [comment]
OK. `khi_robot` uses `prerelease` at the begging.
I'll accept this PR.
Thanks! @k-okada @gavanderhoorn

**Comment by gavanderhoorn** [comment]
@d-nakamichi @k-okada: this PR included a lot of my commits. I would have appreciated it if #5 could have been merged instead. Now changes to the packaging and build setup are merged from a PR that is unrelated (ie: one that "update[s] travis.yml").

This cannot be fixed now any more, but in the future please do not do this with my pull requests.

**Comment by gavanderhoorn** [comment]
> > @k-okada: did you have any particular reason not to use industrial_ci?
> 
>     1. ros_buildfarm is less likely to loose maintainer, If ros_buildfarm is orphaned and we have no alternatives, that’s mean the end of ROS. For example, every time we have new ROS distro or new Ubuntu version, we can assume it is OSRF jobs to update the ros_buildfirm to support them. But as for industrial_ci, someone have to do that.

I don't really follow your argument here.

Are you worried about whether `industrial_ci` will be maintained in the future?

> (In my opinion, if ROS-I have the resource to maintain industrial_ci that effort should goes to maintain image_pipeline, rqt, ros-drivers,,, and so on...)

I guess we don't agree here: ROS-Industrial is not responsible for maintaining all sorts of packages. Resources are limited everywhere, so we have to make choices.

`industrial_ci` fulfils a direct need of ROS-Industrial members, so it makes sense to spend effort there.

>     2. My understanding of industrial_ci is customizable, (At least originally, because that is originally coms from our [http://github.com/jsk-ros-pkg/jsk_travis](https://github.com/jsk-ros-pkg/jsk_travis) ) So when the source tree did not pass the travis we have opetion to customize the CI parts, for example skip some package, run extra scripts and so on...., and it is good compromise between stability vs development speed, for research labs. But for industrial application, stability is much important. So if we do not pass the travis, we should fix source tree.  (So ideally, we should run build script, in addition to prerelease, because our intrest is if the source tree is able to run on the buildfirm.)

re: customizable -> for research labs: I don't fully understand your reasoning here. `industrial_ci` supports running prereleases as well as many other things. Changing `.travis.yml` for `industrial_ci` has to go through the same process (ie: a pull request that should be reviewed) as with the current setup.

What you write are maintenance policy / development process concerns. All software is customisable, and I doubt `industrial_ci` is any more customisable than the current `.travis.yml`. In either case: no maintainer can just go in and chance CI configuration, unless the repository has been badly configured.

**Comment by k-okada** [comment]
@gavanderhoorn Then, what is the reason for having `industrial_ci`? in addition to the prerelease.py ?

**Comment by gavanderhoorn** [comment]
> @gavanderhoorn Then, what is the reason for having `industrial_ci`? in addition to the prerelease.py ?

I believe it would a bit too much to discuss this in a comment.

I'd refer you to the [readme](https://github.com/ros-industrial/industrial_ci/blob/master/README.rst) and the rest of the documentation.

For me personally, *readability* of the travis configuration is a big plus. Compare: [this](https://github.com/Kawasaki-Robotics/khi_robot/blob/e2366feeaca3e000c715d3f7f24d97a1814766c5/.travis.yml) with [this](https://github.com/gavanderhoorn/khi_robot/blob/9fcddd0e26863616fb9382ffb6685eebae6dfc7e/.travis.yml) (if pinning of `industrial_ci` is a concern, specify a version [here](https://github.com/gavanderhoorn/khi_robot/blob/9fcddd0e26863616fb9382ffb6685eebae6dfc7e/.travis.yml)).

Please note that I don't feel strongly about this. If you're happy with what you're using right now then please keep using that :)

**Comment by k-okada** [comment]
> For me personally, readability of the travis configuration is a big plus.
Compare: this with this (if pinning of industrial_ci is a concern, specify
a version here).

If that is the problem, prepare one script and write `curl -sL ttps://
raw.github.com/ros-industrial/industrial_ci/master/run_prerelease.sh |
bash` in travis.yml

> Please note that I don't feel strongly about this.

Yeah, I know.

**Pull request merged**
