### PR TITLE
Add rs013n

### PR DESCRIPTION
**Pull request by matsui-hiro**
Add rs013n pkgs for Gazebo and real robot.

### CODE REVIEW

**Comment by d-nakamichi** [comment]
Could you apply #44 modification to this rs013n?
Maybe it needs to modify `khi_robot_bringup/launch/rs013n_bringup.launch` about `xacro`

**Comment by matsui-hiro** [comment]
@d-nakamichi  OK.
I fixed `khi_robot_bringup/launch/rs013n_bringup.launch` to use xacro instead of xacro.py.

**Comment by matsui-hiro** [comment]
Travis's RS013N test program failed because of collision .Modified test program for RS013N.

**Comment by d-nakamichi** [comment]
OK. Thank you.
Now I understand that Kinetic is EOL and the travis's test is also EOL.

**Pull request merged**
