### PR TITLE
Bugfix for noetic release

### PR DESCRIPTION
**Pull request by sktometometo**

### CODE REVIEW

**Comment by sktometometo** [comment]
The khi_robot packages can be built after the noetic release of moveit https://github.com/ros/rosdistro/commit/d8828c943a8c7c9725ace53be6b1eb066cdce40f.

Some tests still seem to fail though.

> ubuntu@37f1d085f80f:~/ws_khi_robot$ catkin_make test
> Base path: /home/ubuntu/ws_khi_robot
> Source space: /home/ubuntu/ws_khi_robot/src
> Build space: /home/ubuntu/ws_khi_robot/build
> Devel space: /home/ubuntu/ws_khi_robot/devel
> Install space: /home/ubuntu/ws_khi_robot/install
> ####
> #### Running command: "make cmake_check_build_system" in "/home/ubuntu/ws_khi_robot/build"
> ####
> ####
> #### Running command: "make test -j8 -l8" in "/home/ubuntu/ws_khi_robot/build"
> ####
> Running tests...
> Test project /home/ubuntu/ws_khi_robot/build
>       Start  1: _ctest_khi_duaro_description_roslaunch-check_tests_roslaunch_test_duaro.xml
>  1/13 Test  #1: _ctest_khi_duaro_description_roslaunch-check_tests_roslaunch_test_duaro.xml ...............   Passed    1.18 sec
>       Start  2: _ctest_khi_duaro_moveit_config_roslaunch-check_tests_roslaunch_test_moveit_duaro.xml
>  2/13 Test  #2: _ctest_khi_duaro_moveit_config_roslaunch-check_tests_roslaunch_test_moveit_duaro.xml ......   Passed    1.59 sec
>       Start  3: _ctest_khi_rs_description_roslaunch-check_tests_roslaunch_test_rs007l.xml
>  3/13 Test  #3: _ctest_khi_rs_description_roslaunch-check_tests_roslaunch_test_rs007l.xml .................   Passed    1.15 sec
>       Start  4: _ctest_khi_rs_description_roslaunch-check_tests_roslaunch_test_rs007n.xml
>  4/13 Test  #4: _ctest_khi_rs_description_roslaunch-check_tests_roslaunch_test_rs007n.xml .................   Passed    1.18 sec
>       Start  5: _ctest_khi_rs_description_roslaunch-check_tests_roslaunch_test_rs080n.xml
>  5/13 Test  #5: _ctest_khi_rs_description_roslaunch-check_tests_roslaunch_test_rs080n.xml .................   Passed    1.16 sec
>       Start  6: _ctest_khi_rs007l_moveit_config_roslaunch-check_tests_roslaunch_test_moveit_rs007l.xml
>  6/13 Test  #6: _ctest_khi_rs007l_moveit_config_roslaunch-check_tests_roslaunch_test_moveit_rs007l.xml ....   Passed    1.55 sec
>       Start  7: _ctest_khi_rs007n_moveit_config_roslaunch-check_tests_roslaunch_test_moveit_rs007n.xml
>  7/13 Test  #7: _ctest_khi_rs007n_moveit_config_roslaunch-check_tests_roslaunch_test_moveit_rs007n.xml ....   Passed    1.52 sec
>       Start  8: _ctest_khi_rs080n_moveit_config_roslaunch-check_tests_roslaunch_test_moveit_rs080n.xml
>  8/13 Test  #8: _ctest_khi_rs080n_moveit_config_roslaunch-check_tests_roslaunch_test_moveit_rs080n.xml ....   Passed    1.52 sec
>       Start  9: _ctest_khi_robot_control_rostest_tests_test_main.xml
>  9/13 Test  #9: _ctest_khi_robot_control_rostest_tests_test_main.xml ......................................   Passed    8.80 sec
>       Start 10: _ctest_khi_robot_test_rostest_tests_khi_robot_control_test_khi_robot_control_duaro.xml
> 10/13 Test #10: _ctest_khi_robot_test_rostest_tests_khi_robot_control_test_khi_robot_control_duaro.xml ....***Failed    0.77 sec
>       Start 11: _ctest_khi_robot_test_rostest_tests_khi_robot_control_test_khi_robot_control_rs007n.xml
> 11/13 Test #11: _ctest_khi_robot_test_rostest_tests_khi_robot_control_test_khi_robot_control_rs007n.xml ...***Failed    0.76 sec
>       Start 12: _ctest_khi_robot_test_rostest_tests_khi_robot_control_test_khi_robot_control_rs007l.xml
> 12/13 Test #12: _ctest_khi_robot_test_rostest_tests_khi_robot_control_test_khi_robot_control_rs007l.xml ...***Failed    0.76 sec
>       Start 13: _ctest_khi_robot_test_rostest_tests_khi_robot_control_test_khi_robot_control_rs080n.xml
> 13/13 Test #13: _ctest_khi_robot_test_rostest_tests_khi_robot_control_test_khi_robot_control_rs080n.xml ...***Failed    0.76 sec
> 
> 69% tests passed, 4 tests failed out of 13
> 
> Total Test time (real) =  22.70 sec
> 
> The following tests FAILED:
>          10 - _ctest_khi_robot_test_rostest_tests_khi_robot_control_test_khi_robot_control_duaro.xml (Failed)
>          11 - _ctest_khi_robot_test_rostest_tests_khi_robot_control_test_khi_robot_control_rs007n.xml (Failed)
>          12 - _ctest_khi_robot_test_rostest_tests_khi_robot_control_test_khi_robot_control_rs007l.xml (Failed)
>          13 - _ctest_khi_robot_test_rostest_tests_khi_robot_control_test_khi_robot_control_rs080n.xml (Failed)
> Errors while running CTest
> make: *** [Makefile:130: test] Error 8
> Invoking "make test -j8 -l8" failed

**Comment by sktometometo** [comment]
Fails of tests on noetic seem to be due to changes of the return value of MoveGroupCommander.plan().
melodic (https://github.com/ros-planning/moveit/blob/783f6b4e990facd8bf2eabc16828db9661b4d1c6/moveit_commander/src/moveit_commander/move_group.py#L505-L520) and noetic (https://github.com/ros-planning/moveit/blob/3cc363372a6e52d378e6907096979ccff49cdccf/moveit_commander/src/moveit_commander/move_group.py#L508-L532)

**Comment by sktometometo** [comment]
In noetic with armhf, gazebo_ros package seems not to be released. ( build failed http://build.ros.org/job/Nbin_ufhf_uFhf__gazebo_ros__ubuntu_focal_armhf__binary/ )
Fails of noetic test on armhf is due to this package.

**Comment by sktometometo** [comment]
gazebo_ros depends on gazebo_dev package, and gazebo_dev package depends on gazebo.
In focal (20.04), rosdep 'gazebo' entry refer to gazebo11. But gazebo11 is not released in osrf repository. http://repositories.ros.org/ubuntu/building/dists/focal/main/binary-armhf/Packages

I cannot find CI information about the osrf repository.
But build of gazebo9 in the ubuntu official repo for armhf fails because libqtpropertybrowser-dev is not released for armhf in focal.

**Comment by sktometometo** [comment]
Asking https://github.com/osrf/gazebo/issues/2857

**Comment by sktometometo** [comment]
rebased on origin/master and remove armhf support.

**Comment by sktometometo** [comment]
Seems that this works in simulation mode and gazebo.

**Comment by k-okada** [comment]
@sktometometo thanks!

**Review by d-nakamichi — APPROVED** [review]
Thank you. This enables the driver to work well in Noetic!

**Review by matsui-hiro — APPROVED** [review]

**Pull request merged**
