### PR TITLE
Prefix all pkgs with 'khi_'

### PR DESCRIPTION
**Pull request by d-nakamichi**
This PR converts all of packages to `khi_*` for #4 
It changes only package(directory) names.

### CODE REVIEW

**Comment by d-nakamichi** [comment]
I rebased on master to solve a conflict.

@matsui-hiro I think `master` currently has a problem about https://github.com/Kawasaki-Robotics/khi_robot/pull/8#issuecomment-479585050 
Please consider to fix it.

**Comment by gavanderhoorn** [comment]
@d-nakamichi wrote:
> It changes only package(directory) names.

the PR seems to change more than just the directory names, correct?

I would also expect there to be more changes needed.

**Comment by d-nakamichi** [comment]
@gavanderhoorn 

> the PR seems to change more than just the directory names, correct?

Is that means it changes codes of package references like [this](https://github.com/Kawasaki-Robotics/khi_robot/pull/10/files#diff-c0ec1bd217a96522e4c62dfd7fb44370), right?
`It changes package(directory) names and those referenced codes.` may be correct.

> I would also expect there to be more changes needed.

I've already check it OK to build and execute moveit demo, although I'm concerned about https://github.com/Kawasaki-Robotics/khi_robot/pull/8#issuecomment-479585050 (this is about urdf/srdf robot name)
What the expected changes, for example?

**Comment by gavanderhoorn** [comment]
All references to the old package names would need to be replaced with the new names.

For MoveIt configurations, it *may* be easier to just recreate them (as they're mostly auto-generated anyway by the Setup Assistant).

For the rest of the packages: if you've compile tested this (and Travis has done that as well) *and* tested the launch files things should be fine.

We might want to add more `roslaunch` tests to automatically test whether `roslaunch` can still find all the packages, just as I did in #5.

**Comment by d-nakamichi** [comment]
OK. I changed launch files in `khi_*_moveit_config/` based on MoveIt! Setup Assistant.
I also added test files which launch moveit applications.
Thank you.

**Pull request merged**
